- name: backup running configs
  hosts: ios,junos
  gather_facts: no
  become: no

  tasks:
    - name: backup using cli_config
      vars:
        ansible_connection: ansible.netcommon.network_cli
      ansible.netcommon.cli_config:
        backup: true
        backup_options:
          dir_path: backups
          filename: "{{ inventory_hostname }}.cfg"

