- name: Configure dns
  hosts: ios,junos
  gather_facts: no
  become: yes

  tasks:
    - name: Configure dns on ios
      when: ansible_network_os == 'cisco.ios.ios'
      ansible.builtin.include_tasks: tasks/dns_cisco.yml

    - name: Enable netconf on junos
      when: ansible_network_os == "junipernetworks.junos.junos"
      ansible.builtin.include_tasks: tasks/enable_netconf_junos.yml

    - name: Configure dns on junos
      when: ansible_network_os == "junipernetworks.junos.junos"
      ansible.builtin.include_tasks: tasks/dns_junos.yml
