- name: gen dns,ntp,syslog configs
  hosts: workstation.lab.example.com
  gather_facts: no
  become: yes
  become_user: student

  tasks:
    - name: generate ios dns,ntp,syslog configs
      vars:
        nameservers: "{{ hostvars[item]['nameservers'] }}"
        ntp_servers: "{{ hostvars[item]['ntp_servers'] }}"
        syslog_servers: "{{ hostvars[item]['syslog_servers'] }}"
      loop: "{{ groups['ios'] }}" 
      ansible.builtin.template:
        src: "templates/ios.j2"
        dest: "{{ playbook_dir }}/configs/{{ item }}.cfg"

    - name: generate junos dns,ntp,syslog configs
      vars:
        nameservers: "{{ hostvars[item]['nameservers'] }}"
        ntp_servers: "{{ hostvars[item]['ntp_servers'] }}"
        syslog_servers: "{{ hostvars[item]['syslog_servers'] }}"
      loop: "{{ groups['junos'] }}"
      ansible.builtin.template:
        src: "templates/junos.j2"
        dest: "{{ playbook_dir }}/configs/{{ item }}.cfg"
