- name: configure ios interfaces
  cisco.ios.ios_interfaces:
    state: merged
    config:
      - name: "{{ item['name'] }}"
        description: "{{ item['description'] }}"
  loop: "{{ interfaces[inventory_hostname] }}"
