- name: Enable junos netconf
  vars:
    ansible_connection: ansible.netcommon.network_cli
  junipernetworks.junos.junos_netconf:
    netconf_port: 830
    state: present

- name: Add junos interfaces
  junipernetworks.junos.junos_interfaces:
    state: merged
    config:
      - name: "{{ item['name'] }}"
        units: 
        - name: "{{ item['unit_name'] }}"
          description: "{{ item['unit_description'] }}"
  loop: "{{ interfaces[inventory_hostname] }}"
  
