snmp_config:
  location: 'Raleigh, NC'
  contact: 'Network Engineering | neteng@company.com'
  communities:
    - name: rocommunity2n4g!
      authorization: read-only
    - name: rwcommunityd7g$v
      authorization: read-write

