download_url: https://hub.lab.example.com/api/galaxy/v3/plugin/ansible/content/rh-certified/collections/artifacts/ansible-utils-2.7.0.tar.gz
format_version: 1.0.0
name: utils
namespace: ansible
server: https://hub.lab.example.com/api/galaxy/content/rh-certified/
signatures:
- pubkey_fingerprint: 39B5D759361A97464C564A8FE1A4BD708A828AAD
  pulp_created: '2023-10-27T09:35:28.547637Z'
  signature: '-----BEGIN PGP SIGNATURE-----

    Version: GnuPG v1


    iQIVAwUAY2QAqeGkvXCKgoqtAQhjPRAAoMHloKTztLB+zVnCjkWckvRiqo5hp88w

    MXcfvPsDjYfYN+rfgDDF/UBPhfZUpmT3QFpN35E5AbO9osa4IiEZyS/vUaPULeEe

    WqtLForhigJcbujQ64IhJpXlEtm6YQ4UmpV5VjsXHP4eblzYibzPf48t+ygffe0H

    +k8vKKIXSOMCnyH8zVo89H24PBpT5YmrvwEE3yNO73kpZmbWZp8JLEQa3opz2/DN

    tjul+o2vkEoOjfeASEtk2gnAiGCRw/wzdcxtlm3RuaPC1JooBcyoE9niPfVYZLGL

    WXJIDwCpUrbdDqnSI9FCGhnXmdgiroyKPkVtlyZIfcLxElvk7RhkgUaEJWG413Cq

    vq/VMvzF4uoziaPNpqdfHf1EaFxmo/jsl9FMP7lh1MHZEkxl8+Y4L4A+q+Yj5m5T

    L248eLJa8cH2k6UgFk0SXkelw3GymfhUkVwCPn7kzQUhG/CB1HHa2/FHaXENEU8N

    Jrqvw2mT1C50wLiLMS//OHdigN+oO6RIlpMukQbLXP5Iq62+kAb2+bmDEfwMhj7M

    CTTQQHROjfJ60NJN4RmD+zU5lE8G1MkSHkGnJMkjFufWvNj5ZP7WAF/O+hOce9kC

    Q8og5X+Q6cM7kFlR2Z8v1boBF/+IbymKE/v3aa0ZWQcsBsgquzJqPUkdbrw360uh

    UMNyXVmIELU=

    =Cxnl

    -----END PGP SIGNATURE-----

    '
  signing_service: null
version: 2.7.0
version_url: /api/galaxy/content/rh-certified/v3/plugin/ansible/content/rh-certified/collections/index/ansible/utils/versions/2.7.0/
