---
interfaces:
  iosxe1.lab.example.com:
    - name: Loopback0
      description: Managed by Ansible

    - name: GigabitEthernet2
      description: Managed by Ansible

  iosxe2.lab.example.com:
    - name: Loopback0
      description: Managed by Ansible

    - name: GigabitEthernet2
      description: Managed by Ansible
