---
- name: Gather network resource information
  hosts:
    - ios
    - junos
  gather_facts: false
  tasks:
    - name: Facts task
      ansible.builtin.include_tasks:
        file: tasks/{{ ansible_network_os }}.yml

    - name: Configure interface descriptions
      ansible.builtin.include_tasks:
        file: tasks/{{ ansible_network_os }}_interface.yml

    - name: Network Resource Manager
      ansible.builtin.include_role:
        name: network.base.resource_manager
      vars:
        action: gather
        resources:
          - 'interfaces'

    - name: Run a command to verify interface configurations
      vars:
        ansible_connection: ansible.netcommon.network_cli
      ansible.netcommon.cli_command:
        command: "{{ show_interfaces }}"
      register: result

    - name: Display the results
      ansible.builtin.debug:
        var: result['stdout_lines']
