- name: deploy new configs
  hosts: ios,junos
  gather_facts: no
  become: no

  tasks:
    - name: deploy new configs
      when: ansible_network_os == "cisco.ios.ios"
      cisco.ios.ios_config:
        src: "{{ playbook_dir }}/configs/{{ inventory_hostname }}.cfg"

    - name: deplay junos configs
      when: ansible_network_os == "junipernetworks.junos.junos"
      junipernetworks.junos.junos_config:
        src: "{{ playbook_dir }}/configs/{{ inventory_hostname }}.cfg"
