- name: Configure snmp
  hosts: test
  gather_facts: no
  become: yes

  tasks:
    - name: Configure snmp on ios
      when: ansible_network_os == "cisco.ios.ios"
      ansible.builtin.include_tasks: tasks/snmp_ios.yml

    - name: Enable netconf on junos
      when: ansible_network_os == "junipernetworks.junos.junos"
      ansible.builtin.include_tasks: tasks/netconf_junos.yml

    - name: Configure snmp on junos
      when: ansible_network_os == "junipernetworks.junos.junos"
      ansible.builtin.include_tasks: tasks/snmp_junos.yml
