- name: Configure dns on ios
  block:
    - name:  Add dns on ios
      cisco.ios.ios_system:
        name_servers: "{{ name_servers }}"
        domain_search: "{{ domain_search }}"
      register: dns_ios

  rescue:
    - name: display errors
      ansible.builtin.debug:
        var: dns_ios

  always:
    - name: show dns
      cisco.ios.ios_command:
        commands: 
          - show ip name-servers
          - show ip dns view
      register: dns_ios

    - name: display dns ios config
      ansible.builtin.debug:
        var: dns_ios
