- name: Configure dns on junos
  block:
    - name:  Add dns on junos
      junipernetworks.junos.junos_system:
        name_servers: "{{ name_servers }}"
        domain_search: "{{ domain_search }}"
      register: dns_junos

  rescue:
    - name: display errors
      ansible.builtin.debug:
        var: dns_junos

  always:
    - name: show dns
      junipernetworks.junos.junos_command:
        commands: 
          - show configuration system name-server
      register: dns_junos

    - name: display dns config
      ansible.builtin.debug:
        var: dns_junos
