---
- name: Enable the NETCONF service
  vars:
    ansible_connection: ansible.netcommon.network_cli
  junipernetworks.junos.junos_netconf:
    netconf_port: 830
    state: present

- name: Gather Junos facts
  junipernetworks.junos.junos_facts:
    gather_network_resources:
      - interfaces

- name: Save facts to file
  ansible.builtin.copy:
    content: "{{ ansible_facts | to_nice_yaml }}"
    dest: "{{ inventory_hostname }}.txt"
    mode: "0644"
