apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend
  labels:
          app: todonodejs
          name: frontend
spec:
  path: "/todo"
  host: todo.apps.ocp4-mng.example.com
  to:
    kind: Service
    name: prod-frontend
    weight: 100
