---
- name: Generate configuration files from templates
  hosts: workstation.lab.example.com
  become: true
  become_user: student
  gather_facts: false
  vars:
    config_dir: "{{ playbook_dir }}/configs"
  tasks:
    - name: Generate Juniper configuration files
      ansible.builtin.template:
        src: templates/junos.j2
        dest: "{{ config_dir }}/{{ item }}.cfg"
        mode: "0664"
      loop: "{{ groups['junos'] }}"

    - name: Generate Cisco configuration files
      ansible.builtin.template:
        src: templates/ios.j2
        dest: "{{ config_dir }}/{{ item }}.cfg"
        mode: "0664"
      loop: "{{ groups['ios'] }}"
