---
- name: Back up managed network node configurations
  hosts:
    - junos
    - ios
  gather_facts: false
  tasks:
    - name: Back up network managed node configurations
      ansible.builtin.include_role:
        name: net_backup
